version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GL_USER: ${GL_USER}
        GL_PASSWORD: ${GL_PASSWORD}
    ports:
      - "3000:80"
    environment:
      - SUPABASE_PANEL_URL=${SUPABASE_PANEL_URL:-https://efvmshqkpqczrbsilhwu.supabase.co}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

