// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvmshqkpqczrbsilhwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdm1zaHFrcHFjenJic2lsaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjY0MTUsImV4cCI6MjA2ODE0MjQxNX0.-m50oGnybuKF5crwrHbYt8YLo7co5HG027tHM_6CNsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});